image: Visual Studio 2017
configuration: Release
version: '{build}'

dotnet_csproj:
  patch: true
  file: 'GitHubHook\GitHubHook.csproj'
  version: $(appveyor_repo_tag_name)

before_build:
- cmd: dotnet restore

build:
  project: GitHubHook.sln

test_script:
- cmd: >-
    dotnet test GitHubHook.Tests/GitHubHook.Tests.csproj

artifacts:
- path: '**/*.nupkg'
  name: Nuget Packages