image: Visual Studio 2017
configuration: Release
version: '{build}'

install:
- ps: >-
    if ($env:APPVEYOR_REPO_TAG -eq "false")
    {
      $env:COMMIT_DESCRIPTION = git describe --tags
    }
    else
    {
      $env:COMMIT_DESCRIPTION = $env:APPVEYOR_REPO_TAG_NAME
    }
    Write-Host Build version is $env:COMMIT_DESCRIPTION

dotnet_csproj:
  patch: true
  file: 'GitHubHook\GitHubHook.csproj'
  version: $(commit_description)

before_build:
- cmd: dotnet restore

build:
  project: GitHubHook.sln

test_script:
- cmd: >-
    dotnet test GitHubHook.Tests/GitHubHook.Tests.csproj

artifacts:
- path: '**/*.nupkg'
  name: Nuget Packages

deploy:
- provider: NuGet
  api_key:
    secure: SxAkMHv+ymkDs6X4ij1cuxU6mBcXTmtDUCx628rRwb9r/z5hFy6RxRlK4nAzKCgg
  on:
    appveyor_repo_tag: true
